config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tweets#index"
  resources :tweets, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
  resources :comments, only: [:create]
  end
  resources :users, only: [:show]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :tweet
  belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  # association
  belongs_to :user
  has_many :comments
  # validation
  validates_presence_of :image, :text, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # association
  has_many :tweets
  has_many :comments

  # validation
  validates_uniqueness_of :nickname
  validates_presence_of :nickname
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(text: comment_params[:text], tweet_id: comment_params[:tweet_id], user_id: current_user.id)
    redirect_to "/tweets/#{@comment.tweet.id}"
  end

  private
  def comment_params
    params.permit(:text, :tweet_id)
  end
end

app/controllers/comments_cotroller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(text: comment_params[:text], tweet_id: comment_params[:tweet_id], user_id: current_user.id)
    redirect_to "/tweets/#{@comment.tweet.id}"
  end

  private
  def comment_params
    params.permit(:text, :tweet_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
   Like.create(user_id: current_user.id, tweet_id: create_params[:tweet_id])
   redirect_to(:back)
  end

  def destroy
    Like.find_by(user_id: current_user.id, tweet_id: create_params[:tweet_id]).destroy
    redirect_to(:back)
  end

  private
    def create_params
      params.permit(:tweet_id)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :redirect_to_index, :except => [:index]

  def index
    @tweets = Tweet.includes(:user).page(params[:page]).per(5).order("created_at DESC")
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments.includes(:user)
  end

  def new
  end

  def create
    Tweet.create(image: tweet_params[:image], text: tweet_params[:text], user_id: current_user.id)
  end

  def destroy
    tweet = Tweet.find(id_params[:id])
    tweet.destroy if tweet.user_id == current_user.id
  end

  def edit
    @tweet = Tweet.find(id_params[:id])
  end

  def update
    tweet = Tweet.find(id_params[:id])
    tweet.update(tweet_params) if tweet.user_id == current_user.id
  end

  private
  def tweet_params
    params.permit(:image, :text)
  end

  def id_params
    params.permit(:id)
  end

  def redirect_to_index
    redirect_to :action => "index" unless user_signed_in?
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]

  def new
    redirect_to root_path if logged_in?
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:root, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:root, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, only: [:index, :new, :create]
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @nickname = @user.nickname
    @tweets = @user.tweets.page(params[:page]).per(5).order('created_at DESC')
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to :root
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
  def show_params
    params.permit(:id)
  end

  def set_user
    @user = User.find(show_params[:id])
  end

  def user_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def br(str)
    h(str).gsub(/(\r\n?)|(\n)/, "<br />").html_safe
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictweet</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">PicTweet</a></h1>
        <% if logged_in? %>
          <div class="user_nav grid-6">
            <span><%= current_user.nickname %>
              <ul class="user__info">
                <li>
                  <a href="/users/<%= current_user.id %>">マイページ</a>
                  <%= link_to "ログアウト", user_session_path(current_user), method: :delete %>
                </li>
              </ul>
            </span>
            <a class="post" href="/tweets/new">投稿する</a>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, :class => 'post' %>
            <%= link_to "新規登録", new_user_path, :class => 'post' %>
          </div>
        <% end %>
      </div>
    </header>

    <%= yield %>

    <footer>
      <p>
        Copyright PicTweet 2014.
      </p>
    </footer>
  </body>
</html>

app/views/tweet/_tweet.html.erb
<div class="content__post" style="background-image: url(<%= tweet.image %>);">
  <% if current_user && tweet.user_id == current_user.id %>
    <div class="more">
      <span><%= image_tag 'arrow_top.png' %></span>
      <ul class="more_list">
        <li>
          <%= link_to '編集', edit_tweet_path(tweet) %>
        </li>
        <li>
          <%= link_to '削除', tweet_path(tweet), :method => :delete %>
        </li>
      </ul>
    </div>
  <% end %>
  <p>
    <%= br(tweet.text) %>
  </p>
  <span class="name">
    <%=  tweet.likes.count %>
    <% unless Like.exists?(user_id: current_user.id, tweet_id: tweet.id)%>
      <%= form_tag("/likes?tweet_id=#{tweet.id}", :method => :post) do %>
        <input type="submit" value="Like!">
      <% end %>
    <% else %>
      <%= form_tag("/likes/tweet.id/?tweet_id=#{tweet.id}", :method => :delete) do %>
        <input type="submit" value="Not Like!">
      <% end %>
    <% end %>
    <a href="/users/<%= tweet.user_id %>">
      <span>投稿者</span><%= tweet.user.nickname %>
    </a>
  </span>
</div>

app/views/tweets/_tweet.html.erb
<div class="content__post" style="background-image: url(<%= tweet.image %>);">
    <div class="more">
      <span><%= image_tag 'arrow_top.png' %></span>
    <ul class="more_list">
      <li>
        <%= link_to "詳細", tweet_path(tweet.id), method: :get %>
      </li>
      <% if user_signed_in? && current_user.id == tweet.user_id %>
        <li>
          <%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %>
        </li>
      <% end %>
    </ul>
    </div>
    <%= simple_format(tweet.text) %>
  <span class="name">
    <a href="/users/<%= tweet.user_id %>">
      <span>投稿者</span><%= tweet.user.nickname %>
    </a>
  </span>
</div>

app/views/tweets/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      投稿が完了しました。
    </h3>
    <a class="btn" href="/tweets">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      削除が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="contents row">
  <%= form_tag("/tweets/#{@tweet.id}", :method => :patch) do %>
    <h3>
      編集する
    </h3>
    <input placeholder="Image URL" type="text" name="image" value="<%= @tweet.image %>" autofocus="true"></input>
    <textarea placeholder="text" name="text" cols="30" rows="10" ><%= @tweet.text %></textarea>
    <input type="submit" value="SENT">
  <% end %>
</div>

app/views/tweets/index.html.erb
<div class="contents row">
  <% @tweets.each do |t| %>
    <%= render partial: '/tweet/tweet', locals: { tweet: t} %>
  <% end %>
  <%= paginate(@tweets) %>
</div>

app/views/tweets/new.html.erb
<div class="contents row">
  <div class="container">
    <%= form_tag('/tweets', method: :post) do %>
      <h3>
        投稿する
      </h3>
      <input placeholder="Image Url" type="text" name="image">
      <textarea cols="30" name="text" placeholder="text" rows="10"></textarea>
      <input type="submit" value="SENT">
    <% end %>
  </div>
</div>

app/views/tweets/show.html.erb
<div class ="contents row">
  <div class="content__post" style="background-image: url(<%= @tweet.image %>);">
    <% if current_user && @tweet.user_id == current_user.id %>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
      <ul class="more_list">
          <li>
            <%= link_to '削除', "/tweets/#{@tweet.id}", method: :delete %>
          </li>
      </ul>
      </div>
    <% end %>
    <%= simple_format(@tweet.text) %>
    <span class="name">
      <a href="/users/<%= @tweet.user_id %>">
        <span>投稿者</span><%= @tweet.user.nickname %>
      </a>
    </span>
  </div>
  <div class="container">
    <% if current_user %>
      <%= form_tag("/tweets/#{@tweet.id}/comments", method: :post) do %>
        <textarea cols="30" name="text" placeholder="コメントする" rows="2"></textarea>
        <input type="submit" value="SENT">
      <% end %>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <storng><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      編集が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/user_sessions/new.html.erb
<div class="contents row">
  <h2>Log in</h2>

  <%= form_tag user_sessions_path, method: :post  do |f| %>

    <div class="field">
      <%= label_tag :email %><br />
      <%= text_field_tag :email %>
    </div>

    <div class="field">
      <%= label_tag :password %><br />
      <%= password_field_tag :password %>
    </div>

    <div class="actions">
      <%= submit_tag "Log in" %>
    </div>
  <% end %>
</div>

app/views/users/_form.html.erb
<div class="contents row">
  <h2>Sign up</h2>
  <%= form_for @user do |f| %>
    <div class="field">
      <%= f.label :nickname %> <em>(6 characters maximum)</em><br />
      <%= f.text_field :nickname, autofocus: true, maxlength: "6" %>
    </div>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password, autocomplete: "off" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>

    <div class="actions">
      <%= f.submit "Sign up" %>
    </div>
  <% end %>
</div>

app/views/users/likes.html.erb
<div class="contents row">
  <% @likes.each do |l| %>
    <%= render partial: '/tweet/tweet', locals: { tweet: l.tweet} %>
  <% end %>

</div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @nickname %>さんの投稿一覧</p>
  <p><%= link_to 'イイネ', likes_user_path %>
  <%= render @tweets %>
  <%= paginate(@tweets) %>
</div>